destination: ./_site
auto:        true
lsi:         false
server_port: 4000
highlighter: rouge
markdown:    kramdown
permalink:   date
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex
